[project]
name = "miso-in-the-soup"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.4",
    "ollama>=0.6.0",
    "opencv-python>=4.11.0.86",
    "pygame>=2.6.1",
]
